DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file

DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
WARNING:django.request:Not Found: /dashboard/
WARNING:django.request:Not Found: /dashboard
DEBUG:root:This message should go to the log file
ERROR:django.request:Internal Server Error: /default_rule/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/osboxes/admin-interface/admin_interface/configure_rules/views.py", line 12, in default_rule
    return render(request,'dashboard.htm',{'is_authenticated' : 'true'})
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: dashboard.htm
DEBUG:root:This message should go to the log file
ERROR:django.request:Internal Server Error: /default_rule/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/osboxes/admin-interface/admin_interface/configure_rules/views.py", line 12, in default_rule
    return render(request,'default_rule.htm',{'is_authenticated' : 'true'})
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: default_rule.htm
DEBUG:root:This message should go to the log file
ERROR:django.request:Internal Server Error: /default_rule/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/osboxes/admin-interface/admin_interface/configure_rules/views.py", line 12, in default_rule
    return render(request,'default_rule.htm',{'is_authenticated' : 'true'})
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: default_rule.htm
ERROR:django.request:Internal Server Error: /default_rule/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/osboxes/admin-interface/admin_interface/configure_rules/views.py", line 12, in default_rule
    return render(request,'default_rule.htm',{'is_authenticated' : 'true'})
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: default_rule.htm
ERROR:django.request:Internal Server Error: /default_rule/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/osboxes/admin-interface/admin_interface/configure_rules/views.py", line 12, in default_rule
    return render(request,'default_rule.htm',{'is_authenticated' : 'true'})
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: default_rule.htm
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
ERROR:django.request:Internal Server Error: /default_rule/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/osboxes/admin-interface/admin_interface/configure_rules/views.py", line 12, in default_rule
    return render(request,'default_rule.htm',{'is_authenticated' : 'true'})
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: default_rule.htm
DEBUG:root:This message should go to the log file
ERROR:django.request:Internal Server Error: /default_rule/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/osboxes/admin-interface/admin_interface/configure_rules/views.py", line 12, in default_rule
    return render(request,'default_rule.htm',{'is_authenticated' : 'true'})
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR:django.request:Internal Server Error: /default_rule/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/osboxes/admin-interface/admin_interface/configure_rules/views.py", line 12, in default_rule
    return render(request,'default_rule.htm',{'is_authenticated' : 'true'})
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR:django.request:Internal Server Error: /default_rule/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/osboxes/admin-interface/admin_interface/configure_rules/views.py", line 12, in default_rule
    return render(request,'default_rule.htm',{'is_authenticated' : 'true'})
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR:django.request:Internal Server Error: /default_rule/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/osboxes/admin-interface/admin_interface/configure_rules/views.py", line 12, in default_rule
    return render(request,'default_rule.htm',{'is_authenticated' : 'true'})
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
WARNING:django.request:Not Found: /ajax/data/objects.txt
WARNING:django.request:Not Found: /default_rule/static/data/objects.txt
WARNING:django.request:Not Found: /default_rule/static/data/objects.txt
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/home/osboxes/admin-interface/admin_interface/connector/shieldsquare.py", line 34, in process_response
    if request.cookie_values is None:
AttributeError: 'WSGIRequest' object has no attribute 'cookie_values'
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/home/osboxes/admin-interface/admin_interface/connector/shieldsquare.py", line 34, in process_response
    if request.cookie_values is None:
AttributeError: 'WSGIRequest' object has no attribute 'cookie_values'
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
WARNING:django.request:Not Found: /get_redis_rules/
DEBUG:root:This message should go to the log file
WARNING:django.request:Forbidden (CSRF token missing or incorrect.): /get_redis_rules/
WARNING:django.request:Forbidden (CSRF token missing or incorrect.): /get_redis_rules/
DEBUG:root:This message should go to the log file
WARNING:django.request:Forbidden (CSRF token missing or incorrect.): /get_redis_rules/
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
ERROR:django.request:Internal Server Error: /get_redis_rules
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/get_redis_rules/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
DEBUG:root:This message should go to the log file
ERROR:django.request:Internal Server Error: /get_redis_rules
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/get_redis_rules/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
WARNING:django.request:Not Found: /default_rule/get_redis_rules/
DEBUG:root:This message should go to the log file
WARNING:django.request:Not Found: /default_rule/get_redis_rules/
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
WARNING:django.request:Forbidden (CSRF token missing or incorrect.): /get_redis_rules/
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
ERROR:django.request:Internal Server Error: /get_redis_rules/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/osboxes/admin-interface/admin_interface/configure_rules/views.py", line 28, in get_redis_rules
    return JsonResponse(json.dumps(rules))
  File "/usr/local/lib/python2.7/dist-packages/django/http/response.py", line 514, in __init__
    'In order to allow non-dict objects to be serialized set the '
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/home/osboxes/admin-interface/admin_interface/connector/shieldsquare.py", line 34, in process_response
    if request.cookie_values is None:
AttributeError: 'WSGIRequest' object has no attribute 'cookie_values'
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/home/osboxes/admin-interface/admin_interface/connector/shieldsquare.py", line 34, in process_response
    if request.cookie_values is None:
AttributeError: 'WSGIRequest' object has no attribute 'cookie_values'
WARNING:django.request:Forbidden (CSRF cookie not set.): /
WARNING:django.request:Forbidden (CSRF cookie not set.): /
DEBUG:root:This message should go to the log file
DEBUG:root:This message should go to the log file
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/home/osboxes/admin-interface/admin_interface/connector/shieldsquare.py", line 34, in process_response
    if request.cookie_values is None:
AttributeError: 'WSGIRequest' object has no attribute 'cookie_values'
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/home/osboxes/admin-interface/admin_interface/connector/shieldsquare.py", line 34, in process_response
    if request.cookie_values is None:
AttributeError: 'WSGIRequest' object has no attribute 'cookie_values'
